title: "Khadiga Ahmed"
description: "AI Engineer & Data Scientist | Machine Learning • Deep Learning • Computer Vision"
theme: jekyll-theme-cayman

# Author Info
author:
  name: "Khadiga Ahmed"
  email: "khadigahmed899@gmail.com"
  github: "https://github.com/kdjaa"
  linkedin: "https://linkedin.com/in/your-profile"

# Social Links
github:
  is_project_page: true
  repository_url: "https://github.com/kdjaa"

# Build settings
markdown: kramdown
